"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['RM Buddy.py']
DATA_FILES = [('images', ['images/RM_Buddy_logo.png'])]
OPTIONS = {'iconfile':'./resources/RM_Buddy.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
